// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKt1nBqopEruUgtANsRbCTpmyTxS_oKyI',
    appId: '1:735902885479:web:8b292f9efc6e2edb2ad6c2',
    messagingSenderId: '735902885479',
    projectId: 'complaints-sys',
    authDomain: 'complaints-sys.firebaseapp.com',
    storageBucket: 'complaints-sys.appspot.com',
    measurementId: 'G-2KH7JZW2YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhf1Jq7m9i_dws4S_8IcMO--rhTKELupc',
    appId: '1:735902885479:android:0080e457ebaeb2e82ad6c2',
    messagingSenderId: '735902885479',
    projectId: 'complaints-sys',
    storageBucket: 'complaints-sys.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8zRp2NlI_8HZ0Ohr6pBPIWmXmfD6PBEk',
    appId: '1:735902885479:ios:048548ebade889ba2ad6c2',
    messagingSenderId: '735902885479',
    projectId: 'complaints-sys',
    storageBucket: 'complaints-sys.appspot.com',
    iosBundleId: 'com.commadiv.complaintsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8zRp2NlI_8HZ0Ohr6pBPIWmXmfD6PBEk',
    appId: '1:735902885479:ios:048548ebade889ba2ad6c2',
    messagingSenderId: '735902885479',
    projectId: 'complaints-sys',
    storageBucket: 'complaints-sys.appspot.com',
    iosBundleId: 'com.commadiv.complaintsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKt1nBqopEruUgtANsRbCTpmyTxS_oKyI',
    appId: '1:735902885479:web:f5fea38f849effda2ad6c2',
    messagingSenderId: '735902885479',
    projectId: 'complaints-sys',
    authDomain: 'complaints-sys.firebaseapp.com',
    storageBucket: 'complaints-sys.appspot.com',
    measurementId: 'G-CH74KKEBXD',
  );
}
